### PR TITLE
Add SIP permit/deny options

### PR DESCRIPTION
**Pull request by exptom**
It would be useful if we could specify SIP permit/deny params.

### CODE REVIEW

**Comment by lelutin** [comment]
ah, indeed! I wasn't aware yet of those params in sip.conf. knowing what is available in each file is a PITA since documentation is sparse and not super complete out there :|

I just found this post that talks a bit more about security options. Some of the info there is probably out of scope for your PR but they might be interesting to integrate to this module.

http://blogs.digium.com/2009/03/28/sip-security/

As for your changes, to make them actually do something, we'd need to add two blocks of if/content/end in the templates/snippet/sip.erb file that would iterate over values in the two arrays. are you able to quickly add this? if not I can do it in the coming days when I find some time.

**Comment by exptom** [comment]
I've updated the PR with the template.
Totally agree about the asterisk docs - a nightmare, there is so much out of date info around as well!
I think it would be worth adding the additional options in other PRs - I'll try and open some more if I get time.

**Comment by lelutin** [comment]
sweet, thanks for adding that. there was a mistake in the second for loop. it was iterating over `@allow` instead of `@permit` so I added a commit to correct that.
I've tested the change on jessie and wheezy and it looks good.

Thanks for your help!

I've also pushed two commits to add default options for a bit of better default security. `delayreject=yes` in iax.conf and `allowguest=no` and `alwaysauthreject=yes` in sip.conf

**Comment by exptom** [comment]
Thanks @lelutin :-) 
Could you take a version on forge that includes these changes?

**Comment by lelutin** [comment]
@exptom I could! I'd like to clear up one other change before I push another realease, though.

I've opened issues the other day. the one that I'd like to close before the relase would be #5 to make `asterisk::iax` present a bunch of parameters and use a template instead of just having $source or $content.

the change shouldn't be hard to implement but to make it happen I need to find a suitable list of parameters. I might just use the ones that are listed on the page I linked in that issue from asteriskdocs.org to start with.

**Comment by exptom** [comment]
Ok. I'm not using the IAX feature so I don't think I can be a huge help with the parameters.

**Pull request merged**
